# Experiment with `jinjabmi.Jinja`

In [432]:
%load_ext autoreload
%autoreload 2

import sys
import importlib
import numpy as np

import jinjabmi
sys.modules.pop('jinjabmi')
import jinjabmi
#import bmipy_util
#sys.modules.pop('bmipy_util')
#import bmipy_util

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Create a `Jinja` object and initialize the model:

In [433]:
jinja = jinjabmi.Jinja()
jinja.initialize("sample_init.yml")

 call some basic methods:

In [434]:

print("- Input variables:")
print(jinja.get_input_var_names())
print("- Output variables:")
print(jinja.get_output_var_names())

print()

print("- Units of mm_h_rate:")
print(jinja.get_var_units("mm_h_rate"))
print("- Var type of mm_h_rate:")
print(jinja.get_var_type("mm_h_rate"))
print("- Itemsize of mm_h_rate:")
print(jinja.get_var_itemsize("mm_h_rate"))
print("- Total bytes of mm_h_rate:")
print(jinja.get_var_nbytes("mm_h_rate"))


- Input variables:
['mm_h_rate', 'mm_h_rate_grid']
- Output variables:
['mm_accum', 'mm_accum_grid', 'mm_accum_grid_from_scalar']

- Units of mm_h_rate:
mm/h
- Var type of mm_h_rate:
double
- Itemsize of mm_h_rate:
8
- Total bytes of mm_h_rate:
8


Look at the initizialization of random grid data:

In [435]:
display(jinja.get_value_ptr("mm_h_rate"))
display(jinja.get_value_ptr("mm_h_rate_grid"))

array([5.])

array([[5.60943416, 2.92003179],
       [6.50090239, 6.88112943],
       [1.09792962, 2.39564099]])

Call some grid metadata functions:

In [436]:
print("- Grid ID of mm_h_rate:")
grid_id = jinja.get_var_grid("mm_h_rate_grid")
print(grid_id)
print("- Location (on grid) of mm_h_rate_grid:")
print(jinja.get_var_location("mm_h_rate_grid"))
print("- Grid rank of mm_h_rate_grid:")
rank = jinja.get_grid_rank(grid_id)
print(rank)
print("- Grid type of mm_h_rate_grid:")
print(jinja.get_grid_type(grid_id))

print("- Grid shape of mm_h_rate_grid:")
shape = np.zeros((rank), dtype=np.int32)
jinja.get_grid_shape(grid_id, shape)
print(shape)

print("- Grid size of mm_h_rate_grid:")
print(jinja.get_grid_size(grid_id))
print("- Total bytes of mm_h_rate_grid:")
print(jinja.get_var_nbytes("mm_h_rate_grid"))

print("- Grid spacing of mm_h_rate_grid:")
spacing = np.zeros((rank), dtype=np.float64)
jinja.get_grid_spacing(grid_id, spacing)
print(spacing)

print("- Grid origin of mm_h_rate_grid:")
origin = np.zeros((rank), dtype=np.float64)
jinja.get_grid_origin(grid_id, origin)
print(origin)

print("- Grid X's of mm_h_rate_grid:")
#FIXME: This is not correct according to the BMI docs on "ij" indexing.
xlocs = np.zeros((shape[0]), dtype=np.float64)
jinja.get_grid_x(grid_id, xlocs)
print(xlocs)

print("- Grid Y's of mm_h_rate_grid:")
#FIXME: This is not correct according to the BMI docs on "ij" indexing.
ylocs = np.zeros((shape[1]), dtype=np.float64)
jinja.get_grid_y(grid_id, ylocs)
print(ylocs)

- Grid ID of mm_h_rate:
1
- Location (on grid) of mm_h_rate_grid:
node
- Grid rank of mm_h_rate_grid:
2
- Grid type of mm_h_rate_grid:
uniform_rectilinear
- Grid shape of mm_h_rate_grid:
[3 2]
- Grid size of mm_h_rate_grid:
6
- Total bytes of mm_h_rate_grid:
48
- Grid spacing of mm_h_rate_grid:
[1. 1.]
- Grid origin of mm_h_rate_grid:
[0. 0.]
- Grid X's of mm_h_rate_grid:
[0. 1. 2.]
- Grid Y's of mm_h_rate_grid:
[0. 1.]


Override the shape and spacing of a variable:

In [437]:
# using convention-based framework-controled grid shapes...
jinja.set_value("grid_1_shape", np.array([4,5]))
jinja.set_value("grid_1_spacing", np.array([3,3]))
jinja.set_value("grid_1_origin", np.array([1,1]))

Check the metadata again:

In [438]:
print("- Grid ID of mm_h_rate:")
grid_id = jinja.get_var_grid("mm_h_rate_grid")
print(grid_id)
print("- Location (on grid) of mm_h_rate_grid:")
print(jinja.get_var_location("mm_h_rate_grid"))
print("- Grid rank of mm_h_rate_grid:")
rank = jinja.get_grid_rank(grid_id)
print(rank)
print("- Grid type of mm_h_rate_grid:")
print(jinja.get_grid_type(grid_id))

print("- Grid shape of mm_h_rate_grid:")
shape = np.zeros((rank), dtype=np.int32)
jinja.get_grid_shape(grid_id, shape)
print(shape)

print("- Grid size of mm_h_rate_grid:")
print(jinja.get_grid_size(grid_id))
print("- Total bytes of mm_h_rate_grid:")
print(jinja.get_var_nbytes("mm_h_rate_grid"))

print("- Grid spacing of mm_h_rate_grid:")
spacing = np.zeros((rank), dtype=np.float64)
jinja.get_grid_spacing(grid_id, spacing)
print(spacing)

print("- Grid origin of mm_h_rate_grid:")
origin = np.zeros((rank), dtype=np.float64)
jinja.get_grid_origin(grid_id, origin)
print(origin)

print("- Grid X's of mm_h_rate_grid:")
#FIXME: This is not correct according to the BMI docs on "ij" indexing.
xlocs = np.zeros((shape[0]), dtype=np.float64)
jinja.get_grid_x(grid_id, xlocs)
print(xlocs)

print("- Grid Y's of mm_h_rate_grid:")
#FIXME: This is not correct according to the BMI docs on "ij" indexing.
ylocs = np.zeros((shape[1]), dtype=np.float64)
jinja.get_grid_y(grid_id, ylocs)
print(ylocs)



- Grid ID of mm_h_rate:
1
- Location (on grid) of mm_h_rate_grid:
node
- Grid rank of mm_h_rate_grid:
2
- Grid type of mm_h_rate_grid:
uniform_rectilinear
- Grid shape of mm_h_rate_grid:
[4 5]
- Grid size of mm_h_rate_grid:
20
- Total bytes of mm_h_rate_grid:
160
- Grid spacing of mm_h_rate_grid:
[3. 3.]
- Grid origin of mm_h_rate_grid:
[1. 1.]
- Grid X's of mm_h_rate_grid:
[ 1.  4.  7. 10.]
- Grid Y's of mm_h_rate_grid:
[ 1.  4.  7. 10. 13.]


Note that grid data is reinitialized if the shape changes:

In [439]:
display(jinja.get_value_ptr("mm_h_rate_grid"))

array([[5.60943416, 2.92003179, 6.50090239, 6.88112943, 1.09792962],
       [2.39564099, 5.25568081, 4.36751482, 4.96639768, 3.29391214],
       [6.75879595, 6.55558387, 5.1320614 , 7.25448241, 5.93501868],
       [3.28141507, 5.73750157, 3.0822348 , 6.7569006 , 4.90014818]])

Set some input values:

In [440]:
mm_h_rate = 42
jinja.set_value('mm_h_rate', mm_h_rate)


Increment the model by two hours:

In [441]:
jinja.update_until(7200)

Read the output:

In [442]:
output = np.zeros(1)
jinja.get_value('mm_h_rate', output)
display(output)
jinja.get_value('mm_accum', output)
display(output)

display(jinja.get_value_ptr('mm_h_rate'))
display(jinja.get_value_ptr('mm_accum'))

array([42.])

array([84.])

array([42.])

array([84.])

Work with non-scalar values:

In [443]:
jinja.set_value("mm_h_rate_grid", 42.0) # set all cells using a scalar value!

output = np.zeros(20)
jinja.get_value('mm_h_rate_grid', output)
display(output)


array([42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42.,
       42., 42., 42., 42., 42., 42., 42.])

In [444]:
jinja.set_value_at_indices("mm_h_rate_grid", [4,8,12,16], [1, 2, 3, 4])
display(jinja.get_value_ptr('mm_h_rate_grid'))

array([[42., 42., 42., 42.,  1.],
       [42., 42., 42.,  2., 42.],
       [42., 42.,  3., 42., 42.],
       [42.,  4., 42., 42., 42.]])

In [445]:
output_at_indices = np.zeros(3)
jinja.get_value_at_indices("mm_h_rate_grid", output_at_indices, [2,8,14])
display(output_at_indices)

array([42.,  2., 42.])

In [446]:
grid_id = jinja.get_var_grid("mm_accum_grid")
grid_rank = jinja.get_grid_rank(grid_id)
grid_shape = np.zeros(grid_rank, np.int32) # to receive the shape "tuple"
jinja.get_grid_shape(grid_id, grid_shape) # grid_shape now populated

output = np.zeros(tuple(grid_shape)).flatten() #flattened shape
jinja.get_value('mm_accum_grid', output)
display(output.reshape(grid_shape))

array([[84., 84., 84., 84.,  2.],
       [84., 84., 84.,  4., 84.],
       [84., 84.,  6., 84., 84.],
       [84.,  8., 84., 84., 84.]])

Note that grid variables and expressions can be based on scalars--NumPy broadcasting is used:

In [448]:
display(jinja.get_value_ptr("mm_h_rate"))
display(jinja.get_value_ptr("mm_accum_grid_from_scalar"))

array([42.])

array([[84., 84., 84., 84., 84.],
       [84., 84., 84., 84., 84.],
       [84., 84., 84., 84., 84.],
       [84., 84., 84., 84., 84.]])